# Generated by Django 5.0.6 on 2024-07-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacemembers',
            name='display_name',
        ),
    ]
