# Generated by Django 5.0.6 on 2024-07-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_remove_workspacemembers_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemembers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
