# Generated by Django 5.0.6 on 2024-08-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetoonechatmessages',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
    ]
