# Generated by Django 5.0.6 on 2024-08-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_chat', '0002_onetoonechatmessages_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetoonechatmessages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
