# Generated by Django 5.0.6 on 2024-07-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspacegroups',
            old_name='workspace_name',
            new_name='workspace',
        ),
    ]
