# Generated by Django 5.0.6 on 2024-07-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0002_rename_workspace_name_workspacegroups_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegroups',
            name='topic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
