# Generated by Django 5.0.6 on 2024-07-24 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0004_alter_workspacegroups_created_by'),
        ('workspaces', '0004_alter_workspacemembers_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacegroups',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspaces.workspacemembers'),
        ),
    ]
