# Generated by Django 5.0.6 on 2024-08-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0005_alter_workspacegroups_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatmessages',
            name='group',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
