# Generated by Django 5.0.6 on 2024-08-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0010_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatmessages',
            name='read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
